# Generated by Django 4.1.7 on 2023-05-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('course_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_code_for_schedule', to='dropdown.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortcode', models.CharField(max_length=20, unique=True)),
                ('shortcode_bangla', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='dropdown.department')),
            ],
            options={
                'unique_together': {('department', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('exam_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.examsystem')),
            ],
            options={
                'unique_together': {('exam_system', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('exam_year', models.CharField(max_length=10)),
                ('course_schedule', models.ManyToManyField(through='dropdown.CourseSchedule', to='dropdown.course')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.semester')),
            ],
            options={
                'unique_together': {('sem', 'exam_year')},
            },
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.examschedule'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_course', to='dropdown.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('course_code', 'schedule')},
        ),
    ]
